export enum ActionTypePrograms {
  PROGRAM_LIST_REQUEST = "PROGRAM_LIST_REQUEST",
  PROGRAM_LIST_SUCCESS = "PROGRAM_LIST_SUCCESS",
  PROGRAM_LIST_FAIL = "PROGRAM_LIST_FAIL",
  PROGRAM_DELTE_ITEM = "PROGRAM_DELTE_ITEM",
  PROGRAM_DELTE_ITEM_FAIL = "PROGRAM_DELTE_ITEM_FAIL",

  PROGRAM_UPDATE_ITEM = "PROGRAM_UPDATE_ITEM",
  PROGRAM_UPDATE_ITEM_FAIL = "PROGRAM_UPDATE_ITEM_FAIL",

  PROGRAM_CREATE_ITEM = "PROGRAM_CREATE_ITEM",
  PROGRAM_CREATE_ITEM_FAIL = "PROGRAM_CREATE_ITEM_FAIL",


  PROGRAM_SEARCHED_LIST = "PROGRAM_SEARCHED_LIST",
  PROGRAM_SEARCHED_LIST_FAIL = "PROGRAM_SEARCHED_LIST_FAIL",
}
