export enum ActionTypeProgramDetails {
  PROGRAM_DETAILS_REQUEST = "PROGRAM_DETAILS_REQUEST",
  PROGRAM_DETAILS_SUCCESS = "PROGRAM_DETAILS_SUCCESS",
  PROGRAM_DETAILS_FAIL = "PROGRAM_DETAILS_FAIL",
  PROGRAM_DETAILS_CLEAR = "PROGRAM_DETAILS_CLEAR",
}
